# Generated by Django 6.0.3 on 2026-03-21 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_donor_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='donation_type',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='material_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='material_quantity',
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('Money', 'Money'), ('Material', 'Material')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('material_details', models.TextField(blank=True, null=True)),
                ('material_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_logged', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='management.donor')),
            ],
        ),
    ]
