# Generated by Django 6.0.3 on 2026-03-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
