# Generated by Django 6.0.3 on 2026-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_visitor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
