# Generated by Django 6.0.3 on 2026-04-01 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_visit_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
