# Generated by Django 6.0.3 on 2026-04-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_donor_phone_alter_visitor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayWishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('sent_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('phone', 'sent_on')},
            },
        ),
    ]
