# Generated by Django 6.0.3 on 2026-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='medicine_quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='medicine_type',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Tablets', 'Tablets'), ('Injection', 'Injection')], default='Injection', max_length=20),
        ),
    ]
