# Generated by Django 6.0.3 on 2026-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_treatment_medicine_quantity_treatment_medicine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='medicine_quantity',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='medicine_type',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Recovered', 'Recovered')], default='Ongoing', max_length=20),
        ),
    ]
