# Generated by Django 6.0.3 on 2026-04-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_disease_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Recovered', 'Recovered'), ('Death', 'Death')], default='Ongoing', max_length=20),
        ),
    ]
