# Generated by Django 5.0.4 on 2026-03-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Medicine Number or ID', max_length=50)),
                ('date_time', models.DateTimeField(help_text='Date and time of purchase/entry')),
                ('bill_number', models.CharField(max_length=100)),
                ('stia_name', models.CharField(help_text='Staff or Store name', max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medicines',
                'ordering': ['-date_time'],
            },
        ),
    ]
