# Generated by Django 5.0.4 on 2026-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(default='Unknown Medicine', max_length=150),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='number',
            field=models.CharField(help_text='Medicine ID or Batch Number', max_length=50),
        ),
    ]
