# Generated by Django 5.0.4 on 2026-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_medicine_name_medicine_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowFoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Name of food/fodder (e.g., Hay, Silage, Wheat Bran)', max_length=150)),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Quantity in kilograms', max_digits=10)),
                ('supplier', models.CharField(blank=True, help_text='Supplier or vendor name', max_length=150)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_date', models.DateField(help_text='Date of stock purchase')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cow Food Stocks',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
