# Generated by Django 6.0.3 on 2026-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_cowfoodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date of the medicine', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='number_of_store',
            field=models.CharField(blank=True, help_text='Number or name of the store', max_length=100, null=True),
        ),
    ]
