# Generated by Django 6.0.3 on 2026-03-21 13:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_medicine_expiry_date_medicine_number_of_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('usage_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('usage_type', models.CharField(choices=[('Used', 'Used'), ('Defect', 'Defect'), ('Expired', 'Expired')], default='Used', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='inventory.medicine')),
            ],
            options={
                'verbose_name_plural': 'Medicine Usages',
                'ordering': ['-usage_date'],
            },
        ),
    ]
