# Generated by Django 6.0.3 on 2026-03-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medicineusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='number_of_store',
        ),
        migrations.AddField(
            model_name='medicine',
            name='store_phone_number',
            field=models.CharField(blank=True, help_text='Phone number of the store', max_length=100, null=True),
        ),
    ]
