# Generated by Django 6.0.3 on 2026-04-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_medicine_number_of_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='number',
            field=models.CharField(blank=True, default='', help_text='Medicine ID or Batch Number', max_length=50),
        ),
    ]
