# Generated by Django 6.0.3 on 2026-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_cowfoodstock_bill_number_cowfoodstock_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_quantity',
            field=models.CharField(blank=True, help_text='Quantity for bottle (e.g. 500ml)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Tablets', 'Tablets'), ('Injection', 'Injection')], default='Injection', max_length=20),
        ),
    ]
