# Generated by Django 6.0.3 on 2026-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_medicine_medicine_quantity_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('L', 'L'), ('Units', 'Units')], default='Units', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_quantity',
            field=models.CharField(blank=True, help_text='Quantity value for bottle (e.g. 500)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity (bottles/tablets/etc.)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicineusage',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Usage quantity (ml for bottles, units for others)', max_digits=12),
        ),
    ]
