# Generated by Django 6.0.3 on 2026-04-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_medicalstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Tablets', 'Tablets'), ('Injection', 'Injection'), ('Powder', 'Powder'), ('Ointment', 'Ointment')], default='Injection', max_length=20),
        ),
    ]
