# Generated by Django 6.0.3 on 2026-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
