# Generated by Django 5.0.4 on 2026-03-18 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cow',
            options={'ordering': ['-admission_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='cow',
            old_name='name',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='age',
        ),
        migrations.AddField(
            model_name='cow',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cow',
            name='token_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
