# Generated by Django 5.0.4 on 2026-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_alter_cow_options_rename_name_cow_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='mode_of_transport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
