# Generated by Django 5.0.4 on 2026-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_cow_colour_cow_history_cow_mode_of_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Serious', 'Serious')], default='Normal', max_length=20),
        ),
    ]
