# Generated by Django 5.0.4 on 2026-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_cow_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='category',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Bull', 'Bull'), ('Calf', 'Calf'), ('Heifer', 'Heifer'), ('Nandi', 'Nandi')], default='Cow', max_length=20),
        ),
    ]
