# Generated by Django 5.0.4 on 2026-03-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0005_cow_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='owner_name',
            new_name='caller_of_rescue',
        ),
        migrations.RenameField(
            model_name='cow',
            old_name='address',
            new_name='place_of_rescue',
        ),
    ]
