# Generated by Django 6.0.3 on 2026-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0006_rename_rescue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='caller_of_rescue_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='rescuer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
