# Generated by Django 6.0.3 on 2026-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0007_cow_caller_of_rescue_number_cow_rescuer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowBaseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=296)),
                ('cows', models.IntegerField(default=0)),
                ('bulls', models.IntegerField(default=0)),
                ('calves', models.IntegerField(default=0)),
                ('heifer_nandi', models.IntegerField(default=33)),
                ('female', models.IntegerField(default=33)),
                ('male', models.IntegerField(default=95)),
            ],
            options={
                'verbose_name_plural': 'Cow Base Stats',
            },
        ),
    ]
