# Generated by Django 6.0.3 on 2026-03-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0008_cowbasestats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cowbasestats',
            old_name='female',
            new_name='female_calves',
        ),
        migrations.RenameField(
            model_name='cowbasestats',
            old_name='male',
            new_name='male_calves',
        ),
        migrations.RemoveField(
            model_name='cowbasestats',
            name='calves',
        ),
    ]
