# Generated by Django 6.0.3 on 2026-03-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0009_rename_female_cowbasestats_female_calves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowbasestats',
            name='heifer_nandi',
        ),
    ]
